@@include('cabinet-aside.js', {})
@@include('cabinet-application-form.js', {})
@@include('phone-mask.js', {})
@@include('cabinet-file-upload.js', {})
@@include('cabinet-modal.js', {})
@@include('cabinet-steps-logic.js', {})
@@include('pass-validation.js', {})
@@include('show-password.js', {})
